
export {default as Blog} from './blog/blog'
export {default as Event} from './event/event'
export {default as Ecom} from './ecom/ecom'
export {default as MultipleItems} from './photo/recent'
export {default as Team} from './team/team'
export {default as Prem} from './plan/Prem'
export {default as Footer} from './footer/footer'
export {default as Competit} from './competition/competit'
export {default as CountAds} from './countds/countAds'
export {default as Coabou} from './about/coabou'
export {default as Header} from './header/header'